[version]
path = "src/hoist/version.py"

[build.targets.sdist]
exclude = [
  "/.github",
  "/docs",
  "/page",
  "/.mypy_cache",
  "/.venv",
  "/tests",
]
[build.targets.wheel]
packages = ["src/hoist"]

[envs.default]
dependencies = [
  "ward",
  "aiohttp",
  "requests"
]
[envs.default.scripts]
tests = "ward --path tests"
sbuild = "npm run --prefix ./page build && python3 reference.py && hatch run docs:build"
build = "hatch run sbuild && hatch build"

[envs.docs]
dependencies = [
  "mkdocs",
  "mkdocs-material",
]
[envs.docs.scripts]
build = "mkdocs build --clean"
serve = "mkdocs serve --dev-addr localhost:8000"

[[envs.test.matrix]]
python = ["37", "38", "39", "310"]
