site_name: Hoist
site_url: https://example.com/
repo_url: https://github.com/ZeroIntensity/hoist
site_description: Hoist's documentation!

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Reference: reference.md
theme:
  name: material
  locale: en
extra_css: [extra.css]
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      toc_depth: 3
