import string
from typing import List, Optional

import click
from rich import print

from .__about__ import __version__
from .server import Server


@click.command()
@click.option(
    "--token",
    "-t",
    type=str,
    help="Server login token.",
    default=None,
)
@click.option(
    "--host",
    "-h",
    type=str,
    help="Where to host the server.",
    default="0.0.0.0",
    show_default=True,
)
@click.option(
    "--port",
    "-p",
    type=int,
    help="Port to put the server on.",
    default=5000,
    show_default=True,
)
@click.option(
    "--log-level",
    "-l",
    type=int,
    help="Log level to use.",
    default=20,
)
@click.option(
    "--minimum-version",
    "-m",
    type=str,
    help="Minimum version to connect to the server with.",
    default=None,
)
@click.option(
    "--default-len",
    "-d",
    type=int,
    help="Default length of randomly generated key.",
    default=25,
    show_default=True,
)
@click.option(
    "--version",
    "-v",
    help="Display version and exit.",
    is_flag=True,
)
@click.option(
    "--fancy",
    "-f",
    help="Run the server in fancy mode.",
    is_flag=True,
)
@click.option(
    "--support",
    "-s",
    help="Operation to support.",
    multiple=True,
    default=None,
)
@click.option(
    "--unsupport",
    "-u",
    help="Operation to not support.",
    multiple=True,
    default=None,
)
@click.option(
    "--token-string",
    help="String to use for the autogenerated token.",
    default=string.ascii_letters,
    type=str,
)
def main(
    token: Optional[str],
    host: str,
    port: int,
    log_level: int,
    minimum_version: Optional[str],
    default_len: int,
    version: bool,
    fancy: bool,
    support: Optional[List[str]],
    unsupport: Optional[List[str]],
    token_string: str,
) -> None:
    """Start a new Hoist server."""
    if version:
        return print(f"[bold cyan]Hoist {__version__}[/]")

    server = Server(
        token=token,
        log_level=log_level,
        minimum_version=minimum_version,
        default_token_len=default_len,
        fancy=fancy,
        supported_operations=support,
        unsupported_operations=unsupport,
        default_token_choices=token_string,
    )
    server.start(host=host, port=port)


if __name__ == "__main__":
    main()
