name: CI

on:
    push:
        tags:
            - v*
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    wheels-standard:
        name: Build wheels for ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - uses: actions/checkout@v2

            - shell: bash
            run: |
                pip wheel -w wheels .

            - uses: actions/upload-artifact@v2
            with:
                name: artifacts
                path: wheels/*.whl

    pure-python-wheel-and-sdist:
        name: Build a pure Python wheel and source distribution
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  # Fetch all tags
                  fetch-depth: 0

            - name: Install build dependencies
              run: python -m pip install --upgrade build

            - name: Build
              run: python -m build

            - uses: actions/upload-artifact@v2
              with:
                  name: artifacts
                  path: dist/*
                  if-no-files-found: error

    publish:
        name: Publish release
        needs:
            - wheels-standard
            - pure-python-wheel-and-sdist
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')

        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: artifacts
                  path: dist

            - name: Push build artifacts to PyPI
              uses: pypa/gh-action-pypi-publish@v1.4.2
              with:
                  skip_existing: true
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
